image: adoptopenjdk:11-jdk-openj9

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew
  - rm -rf web
  - apt-get update
  - apt-get install git -y
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - build

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle